version: '3.8'

services:

  nginx:
      image: nginx
      container_name: nginx
      ports:
        - 8080:8080
      volumes:
        - ./src:/var/www/html
        - ./nginx/conf:/etc/nginx/
        - ./nginx/logs:/var/log/nginx
      depends_on:
        - php
      networks:
        - camagru
      environment: 
        - NGINX_PORT=80
  php:
      container_name: php
      build:
        context: ./php
        dockerfile: Dockerfile
      volumes:
        - ./src:/var/www/html
        - ./php/conf/:/usr/local/etc
      expose: 
        - 9000
      networks:
        - camagru
      restart: on-failure
  db:
    container_name: db
    image: postgres
    restart: on-failure
    volumes:
      - postgre_db:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 5432:5432


networks:
  camagru:

volumes:
  postgre_db: