version: '3.8'

services:

  nginx:
      image: nginx
      container_name: nginx
      ports:
        - 80:80
      volumes:
        - ./html:/html
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/logs:/var/log/nginx
      depends_on:
        - php
      networks:
        - camagru
  php:
      container_name: php
      build:
        context: ./php
        dockerfile: Dockerfile
      volumes:
        - ./html:/var/www/html
      networks:
        - camagru

networks:
  camagru:
    driver: bridge