version: '3.8'

services:

  nginx:
      container_name: my_nginx
      build:
        context: ./nginx
        dockerfile: Dockerfile
      ports:
        - 8080:8080
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/logs:/var/log/nginx
      depends_on:
        - php
      networks:
        - camagru
  php:
      container_name: my_php
      build:
        context: ./php
        dockerfile: Dockerfile
      volumes:
        - ./html:/var/www/html
      networks:
        - camagru

networks:
  camagru:
    driver: bridge