version: '3.8'

services:

  web:
    image: nginx:latest
    container_name: nginx
    ports:
        - "8080:80"
    volumes:
        - ./src:/code
        - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
        - camagru
    env_file:
        - .env

  php:
      build:
        context: ./php
      container_name: php
      expose: 
        - 9000
      volumes:
        - ./src:/code
      depends_on:
        - db
      networks:
        - camagru
      env_file:
        - .env

  db:
    container_name: db
    image: postgres
    restart: on-failure
    volumes:
      - postgre_db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - camagru
    expose:
      - 5432
    ports:
      - 5432:5432


networks:
  camagru:

volumes:
  postgre_db: